CREATE QUEUE [dbo].[CreateOrderReportTargetQueueWWI]
    WITH POISON_MESSAGE_HANDLING(STATUS = OFF), ACTIVATION (STATUS = ON, PROCEDURE_NAME = [SB].[p_OrderReport_Create_Recieve], MAX_QUEUE_READERS = 1, EXECUTE AS OWNER);

